### ISSUE TITLE
Jobs Listing

### ISSUE THREAD

**Issue by Mastersam07** [Mastersam07/jobby#2]
- Job listing screen
- You could check this [youtube video](https://www.youtube.com/watch?v=ufjmCUNsRO8) for ideas
- You could also check this [github repository](https://github.com/gerfagerfa/job_finder)

**Comment by vikram0230** [comment]
Is there any UI design (Figma/Adobe XD) to work on?

**Comment by Mastersam07** [comment]
None for now. Though, I did reference some youtube vid and Github repo for ideas

**Comment by vikram0230** [comment]
Can I do the UI development?

**Comment by Mastersam07** [comment]
Sure. There are 2 issues tagged `component:ui`. Should I assign both to you? That would be this issue and #1  or I should assign this only?

**Comment by vikram0230** [comment]
Yea, you can assign me to both.

**Comment by Mastersam07** [comment]
@vikram0230 this has been assigned to you. Please drop a comment on #1
