### ISSUE TITLE
List Jobs

### ISSUE THREAD

**Issue by Mastersam07** [Mastersam07/jobby#5]
This should be done after #2 or inconjunction with #2.

Check the API documentation and fetch all jobs. Clicking on a specific job card should open up the job details(call API for that specific job)

**Comment by hutomosaktikartiko** [comment]
> This should be done after #2 or inconjunction with #2.
> 
> Check the API documentation and fetch all jobs. Clicking on a specific job card should open up the job details(call API for that specific job)

has the API to be used been provided?

**Comment by Mastersam07** [comment]
@hutomosaktikartiko Yes. You can check the [wiki](https://github.com/Mastersam07/jobby/wiki/API-Doc)
